// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDReMGKxxs0karpe9yAzx915VYxWLYG0vc',
    appId: '1:1021258541010:web:cf81182f796524d9670a0b',
    messagingSenderId: '1021258541010',
    projectId: 'my-social-app-d5933',
    authDomain: 'my-social-app-d5933.firebaseapp.com',
    storageBucket: 'my-social-app-d5933.appspot.com',
    measurementId: 'G-QY84MNHV6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDILODKOl3u7qGBSC-4Me6FGlu_UuiJ6kc',
    appId: '1:1021258541010:android:f6710391e2f9c8d3670a0b',
    messagingSenderId: '1021258541010',
    projectId: 'my-social-app-d5933',
    storageBucket: 'my-social-app-d5933.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy1EvFAtoNMZOr-wG4vse469J8zOSHO-8',
    appId: '1:1021258541010:ios:e275c37c7b1493f3670a0b',
    messagingSenderId: '1021258541010',
    projectId: 'my-social-app-d5933',
    storageBucket: 'my-social-app-d5933.appspot.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy1EvFAtoNMZOr-wG4vse469J8zOSHO-8',
    appId: '1:1021258541010:ios:e275c37c7b1493f3670a0b',
    messagingSenderId: '1021258541010',
    projectId: 'my-social-app-d5933',
    storageBucket: 'my-social-app-d5933.appspot.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDReMGKxxs0karpe9yAzx915VYxWLYG0vc',
    appId: '1:1021258541010:web:400f709a211a428e670a0b',
    messagingSenderId: '1021258541010',
    projectId: 'my-social-app-d5933',
    authDomain: 'my-social-app-d5933.firebaseapp.com',
    storageBucket: 'my-social-app-d5933.appspot.com',
    measurementId: 'G-311WGB2V54',
  );
}
